version: '3'
services:
  db:
    image: postgres:9.5
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    env_file:
      - db.env
  web:
    build: .
    command: rails s -b '0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - app.env
